project:
  type: website
  execute-dir: project
  preview:
    browser: false

website:
  title: "Food Systems Research Center"
  reader-mode: false
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  repo-url: https://github.com/quarto-dev/quarto-demo
  # announcement:
  #   icon: info-circle
  #   content: "This is a work in progress - all content and analyses are preliminary."
  #   dismissable: true
  #   position: below-navbar
  navbar:
    logo: images/uvm_logo.png
    logo-href: https://www.uvm.edu/cals/food-systems-research
    search: true
    tools:
      - icon: tree
        menu:
          - text: FSRC
            href: https://www.uvm.edu/cals/food-systems-research
          - text: UVM
            href: https://www.uvm.edu
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/Food-Systems-Research-Center/sm-docs
          - text: FSRC GitHub
            href: https://github.com/Food-Systems-Research-Center
  sidebar:
    style: docked
    search: true
    contents:
      - text: Home
        href: pages/01_home.qmd
      - text: Framework
        href: pages/02_framework.qmd
      - text: SM-Explorer
        href: pages/02.1_sm-explorer.qmd
      - section: Dimensions
        contents:
          - text: Economics
            href: pages/03.1_economics.qmd
format:
  html:
    page-layout: article 
    # theme: sandstone
    theme: custom_theme.scss
    fig-align: left
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 2
    code-fold: true
    grid: 
      body-width: 900px
      sidebar-width: 200px
      margin-width: 200px
    # mainfont: Garamond
    smooth-scroll: true
    link-external-newwindow: true
    # linkcolor: DarkOliveGreen
    title-block-style: default

bibliography: fsrc.bib

execute:
  warning: false
  cache: true

