project:
  type: website

website:
  title: "Food System Sustainability Metrics"
  reader-mode: false
  page-navigation: true
  bread-crumbs: false
  navbar:
    search: true
    tools:
      - icon: github
        href: https://github.com/ChrisDonovan307
  sidebar:
    style: docked
    search: true
    contents:
      - text: Home
        href: pages/home.qmd
      - text: Framework
        href: pages/framework.qmd
      - section: Dimensions
        contents:
          - text: 'Environment'
            href: pages/environment.qmd
          - text: 'Economics'
            href: pages/economics.qmd
          - text: 'Production'
            href: pages/production.qmd
          - text: 'Health'
            href: pages/health.qmd
          - text: 'Social'
            href: pages/social.qmd
format:
  html:
    page-layout: article 
    theme: sandstone
    fig-align: left
    css: styles.css
    toc: true
    toc-depth: 2
    # number-sections: true
    # number-depth: 2
    code-fold: true
    grid: 
      # body-width: 900px
      sidebar-width: 200px
      margin-width: 200px

bibliography: 'ref.bib'
