project:
  type: website
  execute-dir: project
  preview: 
    browser: true

website:
  title: "Food Systems Research Center"
  reader-mode: false
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  repo-url: https://github.com/Food-Systems-Research-Center/sm-docs
  navbar:
    logo: images/uvm_logo.png
    logo-href: https://www.uvm.edu/cals/food-systems-research
    search: true
    tools:
      - icon: tree
        menu:
          - text: FSRC
            href: https://www.uvm.edu/cals/food-systems-research
          - text: UVM
            href: https://www.uvm.edu
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/Food-Systems-Research-Center/sm-docs
          - text: FSRC GitHub
            href: https://github.com/Food-Systems-Research-Center
  sidebar:
    title: "Table of Contents"
    style: "docked"
    # search: true
    contents:
      - text: Home
        href: pages/home.qmd
      - section: Framework
        contents: 
          - text: Overview
            href: pages/framework.qmd
          - section: Indicator Refinement
            contents: 
              - text: Economics
                href: pages/refine_economics.qmd
              - text: Environment
                href: pages/refine_environment.qmd
      - section: Secondary Data
        contents:
          - text: Economics
            href: pages/data_economics.qmd
          - section: Environment
            contents:
              - text: Overview
                href: pages/data_environment_overview.qmd
              - text: Maps
                href: pages/data_environment_maps.qmd
              - text: Analysis
                href: pages/data_environment_analysis.qmd
          - text: SM-Explorer
            href: pages/sm-explorer.qmd
          - text: Tables
            href: pages/tables.qmd
      - section: Secondary Data Rework
        contents:
          - text: Framework
            href: pages/refined_framework.qmd

format:
  html:
    page-layout: article 
    theme: custom_theme.scss # modified sandstone
    fig-align: left
    css: styles.css
    toc: true
    toc-title: "On This Page"
    toc-location: right
    toc-depth: 4
    number-sections: true
    number-depth: 4
    code-fold: true
    grid: 
      body-width: 900px
      sidebar-width: 250px
      margin-width: 250px
    mainfont: Roboto
    smooth-scroll: true
    link-external-newwindow: true
    title-block-style: default

bibliography: fsrc.bib

execute:
  warning: false
  cache: true

editor_options:
  chunk_output_type: console